# -*- coding: utf-8 -*-
"""ConsultaValor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QYpJEfEOBVUv1I3Z6aFFkn3teTyGly0X
"""

from bs4 import BeautifulSoup
import requests
import smtplib
import email.message

url = 'https://www.americanas.com.br/produto/3734822003?epar=bp_pl_00_go_wea_pmax_geral_1p&opn=YSMESP&WT.srch=1&gclid=CjwKCAjwjZmTBhB4EiwAynRmD0onK3y453iw-9gzVunsYna0lJtp-eNB-xgwPVsJal9-aQPFjwb1URoCqQIQAvD_BwE&conectividade=GPS&voltagem=BIVOLT'

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'}

site = requests.get(url, headers=headers)

soup = BeautifulSoup(site.content, 'html.parser')

title = soup.find('h1', class_ = 'product-title__Title-sc-1hlrxcw-0 jyetLr').get_text()

print(title)

price = soup.find('div', class_ = 'styles__PriceText-sc-x06r9i-0 dUTOlD priceSales').get_text().strip()

print(price)

num_price =  price [3:8]
num_price = num_price.replace('.','')
num_price = float(num_price)

print(num_price)

def send_email():
  email_content = """
  https://www.americanas.com.br/produto/3734822003?epar=bp_pl_00_go_wea_pmax_geral_1p&opn=YSMESP&WT.srch=1&gclid=CjwKCAjwjZmTBhB4EiwAynRmD0onK3y453iw-9gzVunsYna0lJtp-eNB-xgwPVsJal9-aQPFjwb1URoCqQIQAvD_BwE&conectividade=GPS&voltagem=BIVOLT
  """
  msg = email.message.Message()
  msg['subject'] = 'Preço do Galaxy Watch 4 Baixou!!!'

  msg['From'] = 'origem'
  msg['To'] = 'destinatario'
  password = 'digite a senha'
  msg.add_header('content.type', 'text/html')
  msg.set_payload(email_content)

  s = smtplib.SMTP('smtp.gmail.com: 587')
  s.starttls()
  s.login(msg['From'], password)
  s.sendmail(msg['From'], [msg['To']], msg.as_string())

  print('Sucesso ao enviar e-mail')

if (num_price < 1600):
  send_email()







