# -*- coding: utf-8 -*-
"""ws_feriados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gb-p_z1X3r6z3Ej9o9isx2PMoCXhBsc4
"""

import pandas as pd
import requests

header = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 \
(KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'}

url = 'https://www.anbima.com.br/feriados/fer_nacionais/2022.asp'
request = requests.get(url, headers=header)

df = pd.read_html(request.text)
df

for i , tabela in enumerate(df):
  print('------------------------------------------------------')
  print(i)
  print(tabela)

df = pd.DataFrame(df[2])

df

df.columns = df.iloc[0]

df = df[1:]

df

df.dtypes

df2 = df.copy()

df2.loc[:,'Data'] = pd.to_datetime(df2.loc[:,'Data'])

df2

